### ISSUE TITLE
tests. seperate packages ? 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/pharo-smalltalk#337] opened 2019-05-13 06:30 UTC
on all challenges I see a crititz message that the test class needs to be a seperate package with as end -Tests. 

Do we do something with this ?

**Comment by bencoman** [comment] 2019-05-13 12:54
Our exercises are not big enough to have separate Tests.  We would end up with a lot of exercises having two packages with one class each.  We should disable this QA rule.  @RoelofWobben can you identify the class for this rule - use Tools > Finder > Source to search for some text presented by the rule.

**Comment by RoelofWobben** [comment] 2019-05-13 13:14
oke, I cannot find it but it looks if I look at #326  you found it already

**Comment by bencoman** [comment] 2019-05-13 14:37
yes, this is a duplicate of #326

**Closed by bencoman** 2019-05-13 14:37 UTC
