### ISSUE TITLE
Utility critic rule. Should we disable it? (GeneralRules - Migrated - RBUtilityMethodsRule)  

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/pharo-smalltalk#339] opened 2019-05-14 05:22 UTC
Message on this code : 

```
reverseValue: aCollection
	| result offset |
	result := aCollection species new: aCollection size.
	offset := aCollection size + 1.
	aCollection
		doWithIndex: [ :char :i | result at: offset - i put: char ].
	^ result 
```

**Comment by bencoman** [comment] 2019-05-14 14:21
The issue is more about the Utility Method rule than a particular exercise.  
Can you rename this and condense duplicates to this one?

btw @RoelofWobben, An exercise for you.  Discover which class the rule is in and put that in the title.
i.e. search for source code for the window title
e.g. Tools > Finder > Source ... Utility Method
and it should be the one show the #name method.

**Comment by RoelofWobben** [comment] 2019-05-14 14:36
I see this on these exercises so far 

1) grains 
2) isogram 
3) reverse string 
4) two fer

**Comment by RoelofWobben** [comment] 2019-05-14 15:27
so I think we have to disable it for the whole project

**Comment by bencoman** [comment] 2019-05-14 15:53
yes.  This is simple, doing `RBUtilityMethodsRule enabled: false` as part of the welcome, or a class initialization.  But we should catch everything else is caught up first.

**Comment by RoelofWobben** [comment] 2019-05-14 16:07
oke, can I do this or should you or Tim does this ?

**Comment by macta** [comment] 2019-05-15 01:17
fixed by https://github.com/exercism/pharo-smalltalk/pull/347

**Comment by macta** [comment] 2019-05-15 01:17
needs some clean image testing before doing a release

**Comment by RoelofWobben** [comment] 2019-05-15 12:02
oke, I think this one can be  closed

**Closed** 2019-05-15 21:54 UTC
